version: '3.4'

services:
  admin_nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: examking_admin_nginx
    depends_on:
      - build
    ports:
      - 8081:80
    restart: "always"
    volumes:
      - dist:/var/www/html:rw
  admin_build: 
    build:
      context: ./
      dockerfile: ./docker/build/Dockerfile
    container_name: examking_admin_build
    volumes:
      - dist:/home/examking/dist
      - node_modules:/home/examking/node_modules

volumes: 
  node_modules:
  dist:

networks: # 创建新的网络类型
  examking_net:
    driver: bridge  # 网络方式：桥接或集群