version: '3.4'

services:
  admin_nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: examking_admin_nginx
    depends_on:
      - admin_build
    ports:
      - 8081:80
    restart: "always"
    volumes:
      - admin_dist:/var/www/html:rw
  admin_build: 
    build:
      context: ./
      dockerfile: ./docker/build/Dockerfile
    container_name: examking_admin_build
    volumes:
      - admin_dist:/home/examking_admin/dist
      - admin_node_modules:/home/examking_admin/node_modules

volumes: 
  admin_node_modules:
  admin_dist:

networks: # 创建新的网络类型
  examking_admin_net:
    driver: bridge  # 网络方式：桥接或集群